/// Node database error codes.
const NODE_ALREADY_EXISTS = 'NODE_ALREADY_EXITS';
const NODE_ALREADY_HAS_SERVER = 'NODE_ALREADY_HAS_SERVER';
const NO_AVAILABLE_PORT = 'NO_AVAILABLE_PORT';
const NODE_NOT_FOUND = 'NODE_NOT_FOUND';
const NO_ERROR = '';
