name: distributed.node
description: The user-level interface for distributed.
version: 0.0.1
author: Kendal Harland <kendaljharland@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  distributed.ipc:
    path: ../distributed_ipc
  binary:
  meta:

dev_dependencies:
  test: ^0.12.0
