analyzer:
  strong-mode: true
linter:
  rules:
    - avoid_empty_else
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_getters_setters
    - package_names
