name: distributed
version: 0.0.1
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  distributed.http:
    path: lib/src/http/
  distributed.monitoring:
    path: lib/src/monitoring
  distributed.objects:
    path: lib/src/objects
  async:
  build_runner:
  built_value:
  built_value_generator:
  express:
  fixnum:
  logging:
  meta:
  resource:
  seltzer:
    git: git://github.com/matanlurey/seltzer
  source_gen:
  web_socket_channel: "<=2.0.0"
dev_dependencies:
  dart_style:
  test:
  mockito:
  quiver:
