name: distributed
version: 0.0.1
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  distributed.objects:
    path: lib/src/objects/
  async:
  express:
  fixnum:
  logging:
  meta:
  resource:
  seltzer:
    git: git://github.com/matanlurey/seltzer
  web_socket_channel: "<=2.0.0"
dev_dependencies:
  dart_style:
  test:
  mockito:
  quiver:
  stack_trace:
