name: distributed.utils

version: 0.0.0
description: Utility libraries
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  logging:
dev_dependencies:
  dart_style:
  test:
