name: distributed.port_daemon

version: 0.0.0
description: The distributed_dart port mapping daemon
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  distributed.monitoring:
    path: ../monitoring
  distributed.node:
    path: ../node
  distributed.objects:
    path: ../objects
  web_socket_channel: "<=2.0.0"
  meta:
  fixnum:
  express:
  seltzer:
    git: git://github.com/matanlurey/seltzer.git
dev_dependencies:
  dart_style:
  test:
  mockito:
  quiver:
  echo_server:
    git: git://github.com/kharland/echo_server.git
