name: distributed.connection

version: 0.0.0
description: A library for opening a connection between nodes.
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  distributed.monitoring:
    path: ../monitoring
  distributed.objects:
    path: ../objects
  web_socket_channel: "<=2.0.0"
  meta:
  fixnum:
  express:
  seltzer:
    git: git://github.com/matanlurey/seltzer.git
dev_dependencies:
  dart_style:
  test:
  mockito:
  quiver:
