name: distributed.node

version: 0.0.0
description: A cross-platform distributed-computing framework for dart.
authors:
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/kharland/distributed_dart
dependencies:
  distributed.connection:
    path: ../connection
  distributed.port_daemon:
    path: ../port_daemon
  distributed.utils:
    path: ../utils
  distributed.net:
    path: ../net
  fixnum:
  logging:
  seltzer:
    git: git://github.com/matanlurey/seltzer.git
dev_dependencies:
  quiver:
  dart_style:
  test:
  mockito:
  stack_trace: