name: distributed.ipc
description: Interprocess communication for nodes
version: 0.0.1
author: Kendal Harland <kendaljharland@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  binary:
  meta:

dev_dependencies:
  test: ^0.12.0
